parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: care
    database_user: root
    database_password: epicure
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5d3bef528ec87935be726866Monkeyb710d2c7deb
    database_path: null